name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      job:
        required: true
      comment_id:
        required: true

jobs:
    run-digger:
      runs-on: ubuntu-latest

      permissions:
        contents: write      # required to merge PRs
        id-token: write      # required for workload-identity-federation
        pull-requests: write # required to post PR comments
        statuses: write      # required to validate combined PR status

      steps:
        - name: ${{github.event.inputs.id}}
          run: echo job id ${{ inputs.id }}
        - name: digger run
          uses: diggerhq/digger@vtest-serialization
          with:
            setup-terragrunt: true
            setup-aws: true 
            # you can also use OIDC: https://docs.digger.dev/cloud-providers/authenticating-with-oidc-on-aws
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEBUG: 'true'
